// <auto-generated />
namespace Microsoft.AspNet.Mvc.Razor.Host
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.AspNet.Mvc.Razor.Host.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// Argument cannot be null or empty.
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpy
        {
            get { return GetString("ArgumentCannotBeNullOrEmpy"); }
        }

        /// <summary>
        /// Argument cannot be null or empty.
        /// </summary>
        internal static string FormatArgumentCannotBeNullOrEmpy()
        {
            return GetString("ArgumentCannotBeNullOrEmpy");
        }

        /// <summary>
        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
